"""Generates a synthetic visitor description for a POI using the LLM when Wikipedia returns nothing."""
from __future__ import annotations
import logging

from routeiq.graph.poi import POI

logger = logging.getLogger(__name__)


def describe(poi: POI, city: str) -> str:
    """Return a 2–3 sentence visitor description generated by LLM, or '' on failure."""
    try:
        from routeiq.llm_factory import create_llm
        llm = create_llm()
        kind = poi.subtype or poi.category or "landmark"
        prompt = (
            f"Write a 2–3 sentence visitor description for {poi.name}, "
            f"a {kind} in {city}. "
            f"Focus on what makes it worth visiting and what the experience is like. "
            f"Be factual and concise. Do not mention specific prices or hours."
        )
        result = llm.invoke(prompt)
        text = (result.content if hasattr(result, "content") else str(result)).strip()
        return text
    except Exception as exc:
        logger.warning("Synthetic description failed for %r: %s", poi.name, exc)
        return ""
